from __future__ import annotations

import shutil
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from project_launcher import local_models


@dataclass(frozen=True)
class IngestResult:
    output_path: Path
    message: str


def ingest_file(folder: Path, source: Path) -> IngestResult:
    folder = _require_folder(folder)
    source = _require_source(source)
    suffix = source.suffix.lower()
    if suffix == ".pdf":
        return _write_ingested_note(folder, source, "docs", _extract_pdf_text(source), "PDF text extraction is best-effort and uses local file bytes only.")
    if suffix in {".md", ".txt"}:
        return _write_ingested_note(folder, source, "research", source.read_text(encoding="utf-8", errors="ignore"), "Text file imported locally.")
    if suffix in {".png", ".jpg", ".jpeg", ".webp"}:
        return ingest_image(folder, source)
    if suffix in {".mp3", ".wav", ".m4a"}:
        return ingest_audio(folder, source)
    raise ValueError(f"Unsupported ingest file type: {source.suffix}")


def ingest_image(folder: Path, source: Path) -> IngestResult:
    folder = _require_folder(folder)
    source = _require_source(source)
    prompt = "Describe this product screenshot or design mockup for a product manager. Mention visible UX risks and useful follow-up questions."
    try:
        summary = local_models.describe_image(str(source), prompt)
        limitation = "Image summary generated by a local vision model."
    except local_models.LocalModelUnavailableError:
        summary = (
            "Local vision model is not ready. Add manual notes about this image, or run:\n"
            "ollama pull moondream"
        )
        limitation = "No cloud vision model was used; image content was not interpreted."
    return _write_ingested_note(folder, source, "docs", summary, limitation)


def ingest_audio(folder: Path, source: Path) -> IngestResult:
    folder = _require_folder(folder)
    source = _require_source(source)
    whisper = shutil.which("whisper")
    whisper_cpp = shutil.which("whisper-cli") or shutil.which("main")
    if whisper or whisper_cpp:
        summary = f"Audio file detected at {source}. Local transcription tooling is installed, but automatic transcription is not wired in this CLI yet."
        limitation = "Audio ingestion recorded metadata only in this phase."
    else:
        summary = (
            "Local audio transcription tooling is not ready. Install whisper.cpp or a local Whisper command, "
            "then add the transcript to research/ingested/."
        )
        limitation = "No cloud transcription was used; audio content was not interpreted."
    return _write_ingested_note(folder, source, "research", summary, limitation)


def ingest_folder(folder: Path, source_folder: Path) -> list[IngestResult]:
    folder = _require_folder(folder)
    source_folder = source_folder.expanduser().resolve()
    if not source_folder.exists() or not source_folder.is_dir():
        raise ValueError(f"{source_folder} is not a folder.")
    results: list[IngestResult] = []
    for path in sorted(source_folder.rglob("*")):
        if path.is_file() and path.suffix.lower() in {".pdf", ".md", ".txt", ".png", ".jpg", ".jpeg", ".webp", ".mp3", ".wav", ".m4a"}:
            results.append(ingest_file(folder, path))
    if not results:
        raise ValueError("No supported files found to ingest.")
    return results


def _write_ingested_note(folder: Path, source: Path, target_dir: str, body: str, limitation: str) -> IngestResult:
    ingest_dir = folder / target_dir / "ingested"
    ingest_dir.mkdir(parents=True, exist_ok=True)
    output_path = _unique_path(ingest_dir / f"{source.stem}.md")
    content = "\n".join(
        [
            f"# Ingested: {source.name}",
            "",
            f"- Original file: {source}",
            f"- Ingestion date: {date.today().isoformat()}",
            "- Source marker: local-ingest",
            "",
            "## Extracted Notes",
            "",
            body.strip() or "No extractable text was found.",
            "",
            "## Limitations",
            "",
            limitation,
            "",
        ]
    )
    output_path.write_text(content, encoding="utf-8")
    return IngestResult(output_path=output_path, message=f"Ingested {source.name} to {output_path.relative_to(folder).as_posix()}")


def _extract_pdf_text(source: Path) -> str:
    data = source.read_bytes()
    text = data.decode("utf-8", errors="ignore")
    cleaned = " ".join(text.replace("\x00", " ").split())
    return cleaned[:5000] if cleaned else "PDF text could not be extracted with the standard-library fallback."


def _unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    for index in range(2, 1000):
        candidate = path.with_name(f"{path.stem}-{index}{path.suffix}")
        if not candidate.exists():
            return candidate
    raise ValueError("Could not create a unique ingested filename.")


def _require_folder(folder: Path) -> Path:
    folder = folder.expanduser().resolve()
    if not folder.exists() or not folder.is_dir():
        raise ValueError(f"{folder} is not a project folder.")
    return folder


def _require_source(source: Path) -> Path:
    source = source.expanduser().resolve()
    if not source.exists() or not source.is_file():
        raise ValueError(f"{source} is not a file.")
    return source
